runtime: nodejs20
handlers:
- url: /region-picker
  static_files: index.html
  upload: index.html
  # http_headers are populated from running generate-sha.js
  http_headers:
- url: /region-picker/
  static_files: index.html
  upload: index.html
  # http_headers are populated from running generate-sha.js
  http_headers:
- url: /region-picker/(.+)
  static_files: \1
  upload: (.*)
  # http_headers are populated from running generate-sha.js
  http_headers:
- url: /(.+)
  static_files: \1
  upload: (.*)
  # http_headers are populated from running generate-sha.js
  http_headers:
- url: /
  static_files: index.html
  upload: index.html
  # http_headers are populated from running generate-sha.js
  http_headers: