runtime: nodejs20
handlers:
- url: /region-picker
  static_files: index.html
  upload: index.html
  http_headers:
    Content-Security-Policy: "base-uri 'none'; object-src 'none'; script-src 'self'; connect-src 'self';"

- url: /region-picker/
  static_files: index.html
  upload: index.html
  http_headers:
    Content-Security-Policy: "base-uri 'none'; object-src 'none'; script-src 'self'; connect-src 'self';"
  
- url: /region-picker/(.+)
  static_files: \1
  upload: (.*)
  http_headers:
    Content-Security-Policy: "base-uri 'none'; object-src 'none'; script-src 'self'; connect-src 'self';"

- url: /(.+)
  static_files: \1
  upload: (.*)
  http_headers:
    Content-Security-Policy: "base-uri 'none'; object-src 'none'; script-src 'self'; connect-src 'self';"

- url: /
  static_files: index.html
  upload: index.html
  http_headers:
    Content-Security-Policy: "base-uri 'none'; object-src 'none'; script-src 'self'; connect-src 'self';"
