runtime: nodejs20
handlers:
- url: /region-picker
  static_files: index.html
  upload: index.html

- url: /region-picker/
  static_files: index.html
  upload: index.html
  
- url: /region-picker/(.+)
  static_files: \1
  upload: (.*)

- url: /(.+)
  static_files: \1
  upload: (.*)

- url: /
  static_files: index.html
  upload: index.html
